# Generated by Django 4.2.3 on 2024-01-16 12:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("storename", models.CharField(max_length=10)),
                ("address", models.CharField(max_length=30)),
                ("menu", models.CharField(max_length=10)),
                ("store_phone_number", models.CharField(max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
