# Generated by Django 4.2.3 on 2024-01-16 14:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_store_delete_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="foodimg",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
