# Generated by Django 4.2.3 on 2024-01-16 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_store_comment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="store",
            name="menu",
        ),
        migrations.CreateModel(
            name="StoreMenu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("menu_name", models.CharField(max_length=255)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.store"
                    ),
                ),
            ],
        ),
    ]
