# Generated by Django 4.2.3 on 2024-01-16 16:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_remove_store_menu_storemenu"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomeBannerImg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=20, null=True)),
                ("content", models.CharField(max_length=30, null=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="uploads"),
                ),
            ],
        ),
    ]
