# Generated by Django 4.2.3 on 2024-01-17 05:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0007_alter_homebannerimg_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomeMenuImg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=20)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="homeMenu"),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="homebannerimg",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="banner"),
        ),
    ]
