# Generated by Django 4.2.3 on 2024-01-17 18:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0013_rename_banner_name_homebannerimg_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="delivery_fee",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="store",
            name="min_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="store",
            name="rating",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=3, null=True
            ),
        ),
        migrations.AddField(
            model_name="storemenu",
            name="menu_comment",
            field=models.CharField(default="new", max_length=30),
            preserve_default=False,
        ),
    ]
