# Generated by Django 4.2.3 on 2024-01-18 03:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0014_store_delivery_fee_store_min_price_store_rating_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DishesCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="store",
            name="dishes_categories",
            field=models.ManyToManyField(to="main.dishescategory"),
        ),
    ]
