# Generated by Django 4.2.3 on 2024-01-18 03:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0016_delete_homemenuimg_dishescategory_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dishescategory",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="dishes_category"),
        ),
    ]
