# Generated by Django 4.2.3 on 2024-01-19 17:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0018_alter_customuser_groups_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="storemenu",
            name="img",
            field=models.ImageField(blank=True, null=True, upload_to="store_menus"),
        ),
    ]
